export const SliderData = [
    {
      image:
        'https://i.ytimg.com/vi/RVVMEnhCAaM/maxresdefault.jpg'
    },
    {
      image:
        'https://velox.com.ru/images/publication/Forward-503-full-900x700.png'
    },
    {
      image:
        'https://www.bike-discount.de/media/owgr_1/k23216/k23546/690772_cubebikes2020_1.jpg'
    },
    {
      image:
        'https://www.sefiles.net/merchant/1482/images/site/SP18_HP_ElectraBikes_July11.jpg'
    },
    {
      image:
        'https://trek.scene7.com/is/image/TrekBicycleProducts/Supercaliber_Marquee_6?wid=1200'
    }
  ];